### ISSUE TITLE
Automatic Release (CD)

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/starling-capture#14]
- [x] ~~Detect if the `versionCode` has increased~~ Manually trigger the release process
- [x] Create GitHub Release if the `versionCode` has increased
  - [x] Upload the master build APK to the new GitHub Release and Google Play Console on internal track
- [x] Publish the internal build to Google Play Console
  - [x] Get private variables from GitHub secrets for the internal build
  - [x] Build the signed release AAB
  - [x] Upload to Google Play Console on alpha track
  - [x] Publish to open beta after @bafu create release on GitHub with production tag
- [x] Upload all build variants to Google drive
- [x] Send a message to slack channel once the prerelease has been published

**Comment by scott-dt** [comment]
於slack 上有看到release message
![image](https://user-images.githubusercontent.com/62582260/95811777-92669400-0d46-11eb-8dee-34d13ae7c293.png)
