### ISSUE TITLE
Add information provider toggle

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/starling-capture#18]
**Concept**

If we provide an initial preference setting page

![Starling Capture - UX Wireframes](https://user-images.githubusercontent.com/5687908/88823033-35534b80-d1f7-11ea-8206-5b75ac5d1ed9.jpg)

**Reason/Hypothesis**

We can help users to control privacy better

**Comment by scott-dt** [comment]
collect dev info (off) 
![Screenshot_20200810-142803](https://user-images.githubusercontent.com/62582260/89756746-fafe7e00-db15-11ea-8b9d-15a89c7b5f77.png)

collect location (off) 
![Screenshot_20200810-142751](https://user-images.githubusercontent.com/62582260/89756727-f0dc7f80-db15-11ea-8d64-c7c3fff17677.png)

dev info & location both (off)
![Screenshot_20200810-142833](https://user-images.githubusercontent.com/62582260/89756770-0356b900-db16-11ea-8e36-c0c7bacd2584.png)
