### ISSUE TITLE
[FR] 同一張相片上傳過後加上「已上傳」的標記

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/starling-capture#20]
**Concept**

上傳過後的相片能顯示「已上傳」的標記，讓使用者能很快的知道曾經上傳過的相片有哪些

**Reason/Hypothesis**

避免相同相片因為忘記而被重複上傳 ( 建議在上傳後相片卡可加上 「已上傳」的標記 )

**More Description (if any)**

當相片拍攝很多且上傳過一些之後，下次再使用 app 時沒有辦法在 app上及時的知道曾經上傳的相片，導致重複上傳或 miss 沒有上傳到的狀況發生。建議上傳過後的相片可以加註「已上傳」的標記

**Suggested Implementation (if any)**

- [x] 不管傳到哪裡，在 storage fragment 與 proof fragment 都會顯示以上傳的 mark
- [x] If there is only __one__ publisher is enabled, publish directly without showing the selection dialog.

**Comment by seanwu1105** [comment]
Suggestion: display the dashboard in the app instead of showing the uploaded marks

**Comment by seanwu1105** [comment]
We need to completely redesign the publishing fragments to show the published marks from different publishers. Thus, it requires more time to implement. We need to know:

- Where to show the marks from different publishers
- How to display the confirmation dialog when re-publishing the proof to the _partially overlapped_ publishers

**Comment by scott-dt** [comment]
上船後會顯示 " 上傳的icon "
![Screenshot_20200810-144948](https://user-images.githubusercontent.com/62582260/89757781-d3f57b80-db18-11ea-8612-93220ccdc0b0.png)

**Comment by scott-dt** [comment]
v1.4.1 更新 未設定登入上傳會顯示 " enable publishers settings " 
![Screenshot_20200810-164531](https://user-images.githubusercontent.com/62582260/89765552-22127b00-db29-11ea-9cba-1e8b859a440e.png)
