### ISSUE TITLE
Support CAI format in metadata

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/starling-capture#51]
- [x] Follow the format of date, broad location and precise location in CAI
- [x] Add more location info
- [x] Create Starling schema

**Comment by tammyyang** [comment]
https://gist.github.com/seanwu1105/ab92af7c3c68d0958a4883af198da5e3

**Comment by tammyyang** [comment]
1. Follow Date, Broad Location, Precise Location
2. Add more location info
3. Create Starling schema

**Comment by seanwu1105** [comment]
[The draft of Starling schema](https://gist.github.com/seanwu1105/ab92af7c3c68d0958a4883af198da5e3) for CAI has been updated accordingly.

**Comment by scott-dt** [comment]
![Screenshot_20200910-100318](https://user-images.githubusercontent.com/62582260/92673199-25c63700-f34d-11ea-93de-15d0ebfe2faf.png)
![Screenshot_20200910-100307](https://user-images.githubusercontent.com/62582260/92673202-26f76400-f34d-11ea-8cfe-d5476f470c7d.png)
![Screenshot_20200910-100312](https://user-images.githubusercontent.com/62582260/92673203-278ffa80-f34d-11ea-8969-e443f98d9549.png)

**Comment by wcchung** [comment]
Copy from Slack

--------

@Sean Wu 請問一下 關於 capture beta4 github 中的 issues
#51 支援 CAI 這個項目我要如何進行測試?

Sean Wu  09:58
@Scott Yan 支援 CAI 的測試：
1. Timestamp 改變成 ISO8601
2. 蒐集感應器資訊
3. 蒐集更多地區位置資訊（bearing, altitude 等等）
