### ISSUE TITLE
Create a new build with Numbers Capture UI theme

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/starling-capture#52]
- [x] ~~Use branch instead of build variants.~~
- [x] Build Numbers Capture flavor in new branch.

**Comment by scott-dt** [comment]
1. App launcher icon 換成 capture lite
![Screenshot_20200910-101106](https://user-images.githubusercontent.com/62582260/92673595-0da2e780-f34e-11ea-8698-ec5f8848404e.png)
2. Splash screen 換成 capture lite
![Screenshot_20200910-100952](https://user-images.githubusercontent.com/62582260/92673618-15fb2280-f34e-11ea-8712-14be426b4809.png)
3. 配色換成 capture lite
![Screenshot_20200910-100931](https://user-images.githubusercontent.com/62582260/92673632-1c899a00-f34e-11ea-8779-eb1e6d05a7ef.png)
4. 應該要可以與 starling capture 同時存在在同一台手機中 -> pass 共存且可以同時將兩個app 打開功能正常

**Comment by wcchung** [comment]
Copy from Slack 

--------------------

@Sean Wu 請問一下 關於 capture beta4 github 中的 issues
#52 是指更換ui 的樣式外皮嗎?

Sean Wu  09:58
@Scott Yan 支援 CAI 的測試：
更換 UI：
1. App launcher icon 換成 capture lite
2. Splash screen 換成 capture lite
3. 配色換成 capture lite
4. 應該要可以與 starling capture 同時存在在同一台手機中
