### ISSUE TITLE
Connect account with DIA certificate system

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/starling-capture#53]
(WIP)

## Concept

If we provide \[feature]

## Reason/Hypothesis

We can help \[who] to \[benefit] or solve \[problem] because we know \[who] are \[faced about our target].

## More Description (if any)

Put more description here to support the concept.

## Suggested Implementation (if any)

Put some suggested implementation here if you already have some ideas in mind.

**Comment by seanwu1105** [comment]
Close the issue as the account system does not relate to the app.
