### ISSUE TITLE
Automatically Re-Upload When Internet Connection is Interrupted

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/starling-capture#68]
Retry the publication process with fixed times. No UI change required.

- [x] Retry the publication process with 3 times
- [x] Increase the timeout to 240 seconds
- [x] Show the snack bar message indicating the publication fails with multiple attempts if the uploading process is interrupted

**Comment by bafu** [comment]
Just for note: the interval between two retries is 5 seconds in current implementation.

**Comment by bafu** [comment]
The source codes look good to me.

**Comment by scott-dt** [comment]
電梯中進行測試確定網路不穩的狀況下可自動上傳
sean : WIFI 手動關閉重啟則不會，因為 WiFi 直接中斷而非訊號薄弱，所以在經過兩次5秒鐘間隔，重新嘗試3次後就會顯示失敗訊息。
