### ISSUE TITLE
Launch Starling Capture in Android (close beta)

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/starling-capture#72]
- [x] CD #14 
- [x] Internal Release
- [x] Close Beta

**Comment by seanwu1105** [comment]
Postpone the issue to beta6 as we should finish #14 first.

**Comment by scott-dt** [comment]
![image](https://user-images.githubusercontent.com/62582260/95822889-4ffd8100-0d5f-11eb-9ad2-ff074d20b606.png)
