### ISSUE TITLE
Add ProofMode to Starling Capture

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/starling-capture#73]
- [x] Survey the possibility and capability to integrate ProofMode library in the app
- [x] Add ProofMode library to collect information
- [x] Add a fragment for the configurations about ProofMode library

**Comment by seanwu1105** [comment]
There several issues regarding the integration of ProofMode as the storage permission is getting stricter with the updated Android system: https://github.com/guardianproject/proofmode/issues/75, https://github.com/guardianproject/proofmode/issues/76

**Comment by seanwu1105** [comment]
The `INSTALL_FAILED_NO_MATCHING_ABIS` issue has been solved. However, there is another issue about Gradle dependencies: https://stackoverflow.com/questions/64300437/duplicate-class-okio-in-module-com-eternitywalljava-opentimestamps1-17-with-pr
