### ISSUE TITLE
Add selfie signature as the beta-testing feature in Numbers Capture

### ISSUE THREAD

**Issue by wcchung** [numbersprotocol/starling-capture#76]

**Comment by seanwu1105** [comment]
@wcchung @tammyyang If we want to add the e-signature feature to Capture Pro, it would requires relatively long time to implement and keep the signature pad stable.

**Comment by scott-dt** [comment]
![Screenshot_20201015-154503](https://user-images.githubusercontent.com/62582260/96092538-9a1c6900-0efd-11eb-9712-7cabb14bc248.png)
