### ISSUE TITLE
Support Video Upload for Mediant

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/starling-capture#77]
## Concept

舊版本的影片不能上傳是因為，Textile 並沒有提供 file stream API 來傳大檔案，所以上傳到網路的時候，記憶體會不足。
影像目前無法提供上傳功能

## Reason/Hypothesis

app 中有提供錄影功能 但按上傳按鍵沒有反應

**Comment by seanwu1105** [comment]
This issue has been resolved with the latest Starling Capture (https://github.com/numbersprotocol/starling-capture/issues/66).
