### ISSUE TITLE
[ bug ] 當手機開啟自動旋轉將手機打橫90度開啟相機，會造成 crash

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/starling-capture#82]
## Description

 當手機開啟自動旋轉將手機打橫90度開啟相機，會造成 crash

## Steps to Reproduce

1. 開啟app 並將手機轉90度
2. 點擊 "+" 選取"Built-in camera"
3. 會跳出 「Starling Capture 」已停止運作

## Expected Behavior

* Expected: 相機可正常開啟運行
* Actual: 會跳出 「Starling Capture 」已停止運作 並跳出app

## Logs

![Screenshot_20200923-124200](https://user-images.githubusercontent.com/62582260/93970514-d813ea80-fda0-11ea-8f55-89dcd235a101.png)

## Environment

* Version: 1.6.0
* OS: Android 8.1
* Device: HTC Exodus 1s

**Comment by seanwu1105** [comment]
Same issue: #43
