### ISSUE TITLE
Download Certificate QR Code

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/starling-capture#99]
- [x] Show a placeholder for the certificate QR code to indicate user to publish the digital asset.
- [x] Download the QR code upon user publishing the digital asset and show on the placeholder.
- [x] Save the QR code to external storage if it exists.

**Comment by scott-dt** [comment]
Sean Wu  4:10 PM 之前 sprint kickoff 討論後，現在目標是下載 QR Code 才對，而非有浮水印的圖片。
![Screenshot_20201027-165115](https://user-images.githubusercontent.com/62582260/97278567-e4de9f00-1874-11eb-8438-e1b24c98988c.png)
![Screenshot_20201027-165234](https://user-images.githubusercontent.com/62582260/97278573-e60fcc00-1874-11eb-9b8a-666fd31b6438.png)
